image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get upgrade -y
  - apt-get install git-core rsync -y

build-app:
  stage: build
  only:
    - master
  script:
    - npm i
    - npm run build

deploy-to-github:
  stage: deploy
  only:
    - master
  script:
    - cd ..
    - ls
    - git config --global user.email "${GIT_EMAIL}"
    - git config --global user.name "${GIT_NAME}"
    - git clone https://github.com/stephensprinkle/hi.git hi-github
    - cd hi-github
    - git checkout master
    - rm -rf *
    - cd ../hi/
    - npm i
    - npm run build
    - cp -r . ../hi-github/
    - cp CNAME ../hi-github/docs/
    - cd ../hi-github/
    - git add .
    - git commit -m "Automated deploy commit based on -- $CI_COMMIT_MESSAGE | $CI_COMMIT_SHA"
    - git push https://${GITHUB_USER}:${GITHUB_PAT}@github.com/stephensprinkle/hi.git
