image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get upgrade -y
  - apt-get install git-core rsync -y

build-app:
  stage: build
  only:
    - master
  script:
    - npm i
    - npm run build

deploy-to-github:
  stage: deploy
  only:
    - master
  variables:
    LAST_COMMIT_MSG: 'echo $(git log -1 --pretty=%B)'
    LAST_COMMIT_ID: 'echo $(git log --format="%H" -n 1)'
  script:
    - npm i
    - npm run build
    - git config --global user.email "${GIT_EMAIL}"
    - git config --global user.name "${GIT_NAME}"
    - git clone https://github.com/stephensprinkle/hi.git
    - cd hi
    - git checkout gh-pages
    - rm -rf *
    - cd ..
    - cp ./dist/* hi/
    - cp CNAME hi/
    - cd hi
    - git add .
    - git commit -m "Automated deploy commit based on -- $LAST_COMMIT_MSG | $LAST_COMMIT_ID"
    - git push https://${GITHUB_USER}:${GITHUB_PAT}@github.com/stephensprinkle/hi.git
    - git checkout master
    - rm -rf *
    - cd ..
    - rsync -av --progress . ./hi/ --exclude hi
    - cd hi
    - git add .
    - git commit -m "Automated deploy commit based on -- $LAST_COMMIT_MSG | $LAST_COMMIT_ID"
    - git push https://${GITHUB_USER}:${GITHUB_PAT}@github.com/stephensprinkle/hi.git
