image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get upgrade -y
  - apt-get install git-core rsync -y

build-app:
  stage: build
  only:
    - master
  script:
    - npm i
    - npm run build

deploy-to-github:
  stage: deploy
  only:
    - master
  script:
    - git config --global user.email "${GIT_EMAIL}"
    - git config --global user.name "${GIT_NAME}"
    - git remote set-url origin https://${GITHUB_USER}:${GITHUB_PAT}@github.com/stephensprinkle/hi.git
    - git checkout -b tmp-github
    - npm i
    - npm run build
    - cp CNAME ./docs/
    - git add .
    - git commit -m "CD based on -- $CI_COMMIT_MESSAGE | $CI_COMMIT_SHA"
    - git checkout master
    - git pull
    - git merge tmp-github
    - git push origin HEAD:master
